apiVersion: v1
kind: Endpoints
metadata:
  name: fizz-mysql
  namespace: testing-java
subsets:
  - addresses:
      - ip: 192.168.3.36
    ports:
      - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: fizz-mysql
  namespace: testing-java
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
